apiVersion: v1
kind: ReplicationController
metadata:
  name: mc-dad
spec:
  replicas: 1
  selector:
    name: mc-dad
  template:
    metadata:
      labels:
        name: mc-dad
    spec:
      containers:
      - image: itzg/minecraft-server
        env:
        - name: EULA
          value: "TRUE"
        imagePullPolicy: IfNotPresent
        name: minecraft-server
        ports:
        - containerPort: 25565
        volumeMounts:
          - name: mc-dad
            mountPath: "/data"
      volumes:
      - name: mc-dad
        persistentVolumeClaim:
          claimName: mc-dad
